[project]
name = "librarian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.10.0",
    "langchain[openai]>=0.3.18",
    "tiktoken>=0.8.0",
    "openai>=1.61.1",
    "tqdm>=4.67.1",
]
