[project]
name = "librarian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.18",
    "tiktoken>=0.8.0",
]
